
const MAIN_COLOR_BASE = "#121212";
const MAIN_COLOR_GRADIENT = "#1f1f1f";
const CONTENTWINDOW_COLOR_BASE = "#1f1f1f";
const CONTENTWINDOW_COLOR_GRADIENT = "#121212";


export {MAIN_COLOR_BASE, MAIN_COLOR_GRADIENT, CONTENTWINDOW_COLOR_BASE, CONTENTWINDOW_COLOR_GRADIENT};