
const MAIN_COLOR_BASE = "#222823";
const MAIN_COLOR_GRADIENT = "#2f3b36";
const CONTENTWINDOW_COLOR_BASE = "#2f3b36";
const CONTENTWINDOW_COLOR_GRADIENT = "#222823";


export {MAIN_COLOR_BASE, MAIN_COLOR_GRADIENT, CONTENTWINDOW_COLOR_BASE, CONTENTWINDOW_COLOR_GRADIENT};